import {
    AlertsPage,
    AvatarPage,
    BadgesPage,
    BreadcrumbsPage,
    ButtonsPage,
    CalendarPage,
    CardsPage,
    CarouselPage,
    CheckboxPage,
    ChipsPage,
    CollapsiblePage,
    ColorPickerPage,
    CountdownPage,
    CounterPage,
    // CVPage,
    DashboardPage,
    DatePickerPage,
    DrawerPage,
    FileInputPage,
    ListPage,
    // MaintenancePage,
    MapPage,
    ModalsPage,
    MonthPickerPage,
    // NotFoundPage,
    PaginationPage,
    PopoversPage,
    // ProfilePage,
    ProgressBarPage,
    RadioPage,
    SelectPage,
    SweetAlertsPage,
    SwitchPage,
    TablePage,
    TabsPage,
    TextAreaPage,
    TextFieldPage,
    TimelinePage,
    TooltipsPage,
} from "@/template";
import type { JSX } from "react";
import { FaMapMarkedAlt } from "react-icons/fa";
import {
    PiCalendarBlankFill,
    PiCardsFill,
    // PiFileTextFill,
    PiHouseLineFill,
    PiLightningFill,
    PiTableFill,
    PiTextboxFill,
    // PiUserFill
} from "react-icons/pi";

// Adjust the SubMenu interface to not have a nested sub property
interface SubMenu {
    path: string;
    element: JSX.Element;
    icon?: JSX.Element | null;
    name?: string | JSX.Element | null;
    title?: string;
    sub?: [];
    menuLink?: string;
}

// MenuItem interface with sub as an array of SubMenu
interface MenuItem {
    path?: string;
    element?: JSX.Element | null;
    icon?: JSX.Element;
    name?: string | JSX.Element | undefined;
    title?: string;
    sub?: SubMenu[];
    label?: string;
    menuLink?: string;
    iconActive?: string;
}

export const menu: MenuItem[] = [
    {
        icon: <PiHouseLineFill />,
        path: "/",
        name: "dashboard",
        title: "Dashboard",
        element: <DashboardPage />,
        sub: [],
    },
    {
        label: "USER INTERFACE",
    },
    {
        icon: <PiCardsFill />,
        path: "components",
        name: "components",
        title: "Components",
        element: null,
        sub: [
            {
                icon: null,
                path: "/user-interface/components/cards",
                name: "cards",
                title: "Cards",
                element: <CardsPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/components/carousel",
                name: "carousel",
                title: "Carousel",
                element: <CarouselPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/components/collapsible",
                name: "collapsible",
                title: "Collapsible",
                element: <CollapsiblePage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/components/countdown",
                name: "countdown",
                title: "Countdown",
                element: <CountdownPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/components/counter",
                name: "counter",
                title: "Counter",
                element: <CounterPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/components/drawer",
                name: "drawer",
                title: "Drawer",
                element: <DrawerPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/components/list",
                name: "list",
                title: "List",
                element: <ListPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/components/modals",
                name: "modals",
                title: "Modals",
                element: <ModalsPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/components/sweetalerts",
                name: "sweetalerts",
                title: "SweetAlerts",
                element: <SweetAlertsPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/components/tabs",
                name: "tabs",
                title: "Tabs",
                element: <TabsPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/components/timeline",
                name: "timeline",
                title: "Timeline",
                element: <TimelinePage />,
                sub: [],
            },
        ],
    },
    {
        icon: <PiLightningFill />,
        path: "elements",
        name: "elements",
        title: "Elements",
        element: null,
        sub: [
            {
                icon: null,
                path: "/user-interface/elements/alerts",
                name: "alerts",
                title: "Alerts",
                element: <AlertsPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/elements/avatar",
                name: "avatar",
                title: "Avatar",
                element: <AvatarPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/elements/badges",
                name: "badges",
                title: "Badges",
                element: <BadgesPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/elements/breadcrumbs",
                name: "breadcrumbs",
                title: "Breadcrumbs",
                element: <BreadcrumbsPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/elements/buttons",
                name: "buttons",
                title: "Buttons",
                element: <ButtonsPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/elements/chips",
                name: "chips",
                title: "Chips",
                element: <ChipsPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/elements/pagination",
                name: "pagination",
                title: "Pagination",
                element: <PaginationPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/elements/popovers",
                name: "popovers",
                title: "Popovers",
                element: <PopoversPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/elements/progress-bar",
                name: "progress-bar",
                title: "Progress Bar",
                element: <ProgressBarPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/user-interface/elements/tooltips",
                name: "tooltips",
                title: "Tooltips",
                element: <TooltipsPage />,
                sub: [],
            },
        ],
    },
    {
        icon: <PiCalendarBlankFill />,
        path: "/calendar",
        name: "calendar",
        title: "Calendar",
        element: <CalendarPage />,
        sub: [],
    },
    {
        icon: <FaMapMarkedAlt />,
        path: "/maps",
        name: "maps",
        title: "Maps",
        element: <MapPage />,
        sub: [],
    },
    {
        label: "FORMS & TABLES",
    },
    {
        icon: <PiTextboxFill />,
        path: "forms",
        name: "forms",
        title: "Forms",
        element: null,
        sub: [
            {
                icon: null,
                path: "/form-tables/forms/checkbox",
                name: "checkbox",
                title: "Checkbox",
                element: <CheckboxPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/form-tables/forms/color-picker",
                name: "color-picker",
                title: "Color Picker",
                element: <ColorPickerPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/form-tables/forms/date-picker",
                name: "date-picker",
                title: "Date Picker",
                element: <DatePickerPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/form-tables/forms/file-input",
                name: "file-input",
                title: "File Input",
                element: <FileInputPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/form-tables/forms/month-picker",
                name: "month-picker",
                title: "Month Picker",
                element: <MonthPickerPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/form-tables/forms/radio",
                name: "radio",
                title: "Radio",
                element: <RadioPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/form-tables/forms/select",
                name: "select",
                title: "Select",
                element: <SelectPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/form-tables/forms/switch",
                name: "switch",
                title: "Switch",
                element: <SwitchPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/form-tables/forms/textarea",
                name: "textarea",
                title: "Text Area",
                element: <TextAreaPage />,
                sub: [],
            },
            {
                icon: null,
                path: "/form-tables/forms/textfield",
                name: "textfield",
                title: "Text Field",
                element: <TextFieldPage />,
                sub: [],
            },
        ],
    },
    {
        icon: <PiTableFill />,
        path: "/tables",
        name: "tables",
        title: "Tables",
        element: <TablePage />,
        sub: [],
    },
    // {
    //     label: "USER & PAGES",
    // },
    // {
    //     icon: <PiUserFill />,
    //     path: "users",
    //     name: "users",
    //     title: "Users",
    //     element: null,
    //     sub: [
    //         {
    //             icon: null,
    //             path: "/user-pages/users/curriculum-vitae",
    //             name: "curriculum-vitae",
    //             title: "Curriculum Vitae",
    //             element: <CVPage />,
    //             sub: [],
    //         },
    //         {
    //             icon: null,
    //             path: "/user-pages/users/profile",
    //             name: "profile",
    //             title: "Profile",
    //             element: <ProfilePage />,
    //             sub: [],
    //         },
    //     ],
    // },
    // {
    //     icon: <PiFileTextFill />,
    //     path: "pages",
    //     name: "pages",
    //     title: "Pages",
    //     element: null,
    //     sub: [
    //         {
    //             icon: null,
    //             path: "/user-pages/pages/not-found",
    //             name: "not-found",
    //             title: "404 Not Found",
    //             element: <NotFoundPage />,
    //             sub: [],
    //         },
    //         {
    //             icon: null,
    //             path: "/user-pages/pages/maintenance",
    //             name: "maintenance",
    //             title: "Maintenance",
    //             element: <MaintenancePage />,
    //             sub: [],
    //         },
    //     ],
    // },
];